---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "registry.localho.st"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"


#    hostFromClusterNetwork: "registry.registry.svc.cluster.local"
#    hostFromContainerRuntime: "registry.registry.svc.cluster.local"
