#
# Copyright contributors to the Hyperledger Fabric Operator project
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
# 	  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: ibp.com/v1beta1
kind: IBPPeer
metadata:
  name: peer1
spec:
  version: 2.4.7
  domain: "org3.localho.st"
  peerExternalEndpoint: "org3-peer1-peer.org3.localho.st:443"
  license:
    accept: true
  action:
    enroll: {}
    reenroll: {}
  configoverride:
    peer:
      keepalive:
        minInterval: 61s
  customNames:
    pvc: {}
  images:
    peerInitImage: registry.access.redhat.com/ubi8/ubi-minimal
    peerInitTag: latest
    peerImage: ghcr.io/hyperledger-labs/k8s-fabric-peer
    peerTag: "v0.8.0"
    grpcwebImage: ghcr.io/hyperledger-labs/grpc-web
    grpcwebTag: latest
  mspID: Org3MSP

  # peer1-secret is actually secret.json with: enrollment.*
  mspSecret: peer1-secret
  secret:
    msp:
      tls:
        keystore: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2xCUXFjZjFmZUh2cHZBZDQKREZ3dWxwVnZKcGlER1pPZjlNcVRjVVJkQU5TaFJBTkNBQVQybkkxUDVzeDl4R09WajV1NitvMjdNcEtrdTgxOQoyd29tUk45QXRMMi9lL2FPNkZnVlVzR0dSL3ROTTg3YVk0dTN2ZjBIQnJXS0w3UTNHS3BobFpHRwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
        signcerts: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5ekNDQW5LZ0F3SUJBZ0lVRytNeWM2aDd4RUdDZ3d3NlNNQTBKbnY2aFdZd0NnWUlLb1pJemowRUF3SXcKWURFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1JtRmljbWxqTVJFd0R3WURWUVFERXdoallTMTBiSE5qCllUQWVGdzB5TWpFeE1qTXdNakEyTURCYUZ3MHpNakV4TWpBd01qRXlNREJhTUI4eERUQUxCZ05WQkFzVEJIQmwKWlhJeERqQU1CZ05WQkFNVEJYQmxaWEl4TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOXB5TgpUK2JNZmNSamxZK2J1dnFOdXpLU3BMdk5mZHNLSmtUZlFMUzl2M3YyanVoWUZWTEJoa2Y3VFRQTzJtT0x0NzM5CkJ3YTFpaSswTnhpcVlaV1JocU9DQVVrd2dnRkZNQTRHQTFVZER3RUIvd1FFQXdJRHFEQWRCZ05WSFNVRUZqQVUKQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVbEVzSQoxVFNwV2loUFErcitIVUlNbWgvdkl0TXdId1lEVlIwakJCZ3dGb0FVTU9rSVFoRXFWc255dGp5aWN4bXFiNDRCCmdTa3dnY1VHQTFVZEVRU0J2VENCdW9JZmIzSm5NeTF3WldWeU1TMXdaV1Z5TG05eVp6TXViRzlqWVd4b2J5NXoKZElJbGIzSm5NeTF3WldWeU1TMXZjR1Z5WVhScGIyNXpMbTl5WnpNdWJHOWpZV3hvYnk1emRJSWliM0puTXkxdwpaV1Z5TVMxbmNuQmpkMlZpTG05eVp6TXViRzlqWVd4b2J5NXpkSUlGY0dWbGNqR0NISEJsWlhJeExtOXlaek11CmMzWmpMbU5zZFhOMFpYSXViRzlqWVd5Q0lXOXlaek10Y0dWbGNpMW5ZWFJsZDJGNUxtOXlaek11Ykc5allXeG8KYnk1emRJY0Vmd0FBQVRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBVUFlSlNpSUIrczc3b3lBS21TdTc4MXpCbgp0UGx6dXJoMDdIU2VEbUVWMXdJZ0xGeEpubWZ1TnVuWmpRMnpua3lTd2hSNit5OS9NWW1BSlNYWCt4NUhHTDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
        cacerts:
          - "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNCRENDQWFxZ0F3SUJBZ0lVV2hPK1ZqNnRHQTdKNXgvdThTWnhHOWpIaXdVd0NnWUlLb1pJemowRUF3SXcKWURFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1JtRmljbWxqTVJFd0R3WURWUVFERXdoallTMTBiSE5qCllUQWVGdzB5TWpFeE1qTXdNakEyTURCYUZ3MHpOekV4TVRrd01qQTJNREJhTUdBeEN6QUpCZ05WQkFZVEFsVlQKTVJjd0ZRWURWUVFJRXc1T2IzSjBhQ0JEWVhKdmJHbHVZVEVVTUJJR0ExVUVDaE1MU0hsd1pYSnNaV1JuWlhJeApEekFOQmdOVkJBc1RCa1poWW5KcFl6RVJNQThHQTFVRUF4TUlZMkV0ZEd4elkyRXdXVEFUQmdjcWhrak9QUUlCCkJnZ3Foa2pPUFFNQkJ3TkNBQVNxa1htdE9jMGVhejFiSkFqWDNQb2pYRWtvZTVTZ3YrSGtWRWViZVFzc084aGgKWDcxdElqVmRHVkhSbmp1ZHhWUmx1NVpFdjRVSW5RZGZvbnFYY2pyaW8wSXdRREFPQmdOVkhROEJBZjhFQkFNQwpBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVTU9rSVFoRXFWc255dGp5aWN4bXFiNDRCCmdTa3dDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTS9wZCthWWM2VGk4UW9FMW5xWWZUUjBIY3VNSllyRHdKTWMKUFJKdkdEZHpBaUFVdi9lT2R3M2c2WnVsUis1MGM5amhSQVNlSldiRFBMQnVkempjKzlyaWFnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      component:
        signcerts: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEVENDQWJPZ0F3SUJBZ0lVR1JwUkM4aS8vbXBZS0tOWkduWDlhMzZ1Wldnd0NnWUlLb1pJemowRUF3SXcKWFRFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1JtRmljbWxqTVE0d0RBWURWUVFERXdWallTMWpZVEFlCkZ3MHlNakV4TWpNd01qQTJNREJhRncwek1qRXhNakF3TWpFeU1EQmFNQjh4RFRBTEJnTlZCQXNUQkhCbFpYSXgKRGpBTUJnTlZCQU1UQlhCbFpYSXhNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUV2U1NkUDA0SgpXbmU4bEJuVGJRbGhGYUkyekFIQnpjV3VIbUJWV2xHNkQ4MmRTV2tCU1NzU2JieWtlR3hhUUNZSG5JRTRxTFdVCkN4dDRhaWQrdFlQNjFxT0JqakNCaXpBT0JnTlZIUThCQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWQKQmdOVkhRNEVGZ1FVSytpYW1hOWR5RitpeTJCNy9NaUtWSHY0ZmlZd0h3WURWUjBqQkJnd0ZvQVVYeDl4V3ZHcwo5SmtmYmx0ZVZJLzkxR1BXY0Vnd0t3WURWUjBSQkNRd0lvSWdabUZpY21sakxXOXdaWEpoZEc5eUxUYzNZbU5pCk5UVTROVFl0Y0Rsc1ltMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBUC9SRW1yNEFKdkt2eGpCQ1VoelhzY2QKRENaTG5EaXdIYWFsTjNxUFNQMTFBaUEvcVhkUE1zUVNLSHMzb0IveEFTUVpocWRjNmV5LzQyd0FVSzA4Y3hEOAozUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
        keystore: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1JWRGlmWUtTY2F2VG10KzAKODVhTnIyckt0VWZjMnhFOGFzbjQrOUh1SUc2aFJBTkNBQVM5SkowL1RnbGFkN3lVR2ROdENXRVZvamJNQWNITgp4YTRlWUZWYVVib1B6WjFKYVFGSkt4SnR2S1I0YkZwQUpnZWNnVGlvdFpRTEczaHFKMzYxZy9yVwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
        cacerts:
          - "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEakNDQWJXZ0F3SUJBZ0lVSWtDWFhHWlpGc2ovbWx4UXd0ZC84OXlZQ3BBd0NnWUlLb1pJemowRUF3SXcKWFRFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1JtRmljbWxqTVE0d0RBWURWUVFERXdWallTMWpZVEFlCkZ3MHlNakV4TWpNd01qQTJNREJhRncwek56RXhNVGt3TWpBMk1EQmFNRjB4Q3pBSkJnTlZCQVlUQWxWVE1SY3cKRlFZRFZRUUlFdzVPYjNKMGFDQkRZWEp2YkdsdVlURVVNQklHQTFVRUNoTUxTSGx3WlhKc1pXUm5aWEl4RHpBTgpCZ05WQkFzVEJrWmhZbkpwWXpFT01Bd0dBMVVFQXhNRlkyRXRZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPClBRTUJCd05DQUFTOXhRWGczd1E3dm1nTHNmdFVnRzFTeGs2aFpOZXRMRThSd1gxK0hSNmwvODFldlZiQUc2Q1UKQWRtNmsvbkRrWm9xcFdEQ0FXelhHQUYzK1laRUhxb2hvMU13VVRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVh4OXhXdkdzOUprZmJsdGVWSS85MUdQV2NFZ3dEd1lEClZSMFJCQWd3Qm9jRWZ3QUFBVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFMZ2lXL0pzNFNhVzdKT210OUpCb2oKVEJ4WFViRExUMjR5UjVOVnJzUmtCUUlnWXhuNXRMbEFQWVdRZUtaekVGWlRlNVFnRjFJYUJQaE9JeFkrQUp6RgpGZDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"




  #  secret:
#    enrollment:
#      component:
#        caname: ca
#        cahost: "org3-ca-ca.org3.localho.st"
#        caport: "443"
#        catls:
#          cacert: "${CA_CERT}"
#        enrollid: "peer1"
#        enrollsecret: "peer1pw"
#      tls:
#        caname: tlsca
#        cahost: "org3-ca-ca.org3.localho.st"
#        caport: "443"
#        catls:
#          cacert: "${CA_CERT}"
#        enrollid: "peer1"
#        enrollsecret: "peer1pw"
#        csr:
#          hosts:
#            - "peer1"
#            - "peer1.org3.svc.cluster.local"
#            - "org3-peer-gateway.org3.localho.st"
  chaincodeBuilderConfig:
    peername: org3-peer1
  service:
    type: ClusterIP
  stateDb: leveldb
  storage:
    peer:
      class: "standard"
      size: 5G
    statedb:
      class: "standard"
      size: 10Gi
  resources:
    init:
      limits:
        cpu: 100m
        memory: 200M
      requests:
        cpu: 10m
        memory: 10M
    peer:
      limits:
        cpu: 500m
        memory: 1G
      requests:
        cpu: 10m
        memory: 10M
    proxy:
      limits:
        cpu: 100m
        memory: 200M
      requests:
        cpu: 10m
        memory: 10M